'use strict';

// Backfill `defaults.benefit` (beneficiary user ids, split evenly at
// generation time) for recurring subscriptions.
//
// The pre-2026-04 recurring system copied each generated expense's division
// verbatim from a hidden template expense row, so hand-picked benefit splits
// (e.g. paid from a personal account, benefit shared 50/50) were preserved.
// The subscriptions rework dropped the templates and derived the division
// from the source's default shares instead, silently losing every
// non-default split for rows generated after the rework. `defaults.benefit`
// now pins the beneficiary side again; this backfill restores the original
// intent by taking the beneficiary user ids from each subscription's most
// recent realised expense (all of which were still generated by, or copied
// from, the template-era division data).
//
// `benefit`/`split`/`transferee` is the beneficiary side of the expense /
// income / transfer types respectively; a single expense only ever has one
// of them. Subscriptions with no realised rows are skipped (none exist in
// practice: conversion always links the original expense).
exports.up = knex =>
  knex.raw(/*sql*/ `
    WITH latest AS (
      SELECT DISTINCT ON (e.subscription_id) e.subscription_id, e.id
        FROM expenses e
        WHERE e.subscription_id IS NOT NULL
        ORDER BY e.subscription_id, e.date DESC, e.id DESC
    ),
    beneficiaries AS (
      SELECT l.subscription_id,
             jsonb_agg(DISTINCT ed.user_id ORDER BY ed.user_id) AS benefit
        FROM latest l
        JOIN expense_division ed ON ed.expense_id = l.id
        WHERE ed.type IN ('benefit', 'split', 'transferee')
        GROUP BY l.subscription_id
    )
    UPDATE subscriptions s
      SET defaults = s.defaults || jsonb_build_object('benefit', b.benefit)
      FROM beneficiaries b
      WHERE b.subscription_id = s.id
        AND s.period_unit IS NOT NULL
        AND s.defaults IS NOT NULL
        AND s.defaults -> 'benefit' IS NULL;
  `);

// Down cannot tell backfilled lists from ones the user has since edited in
// the Mallikulu tab, so it drops the key from every recurring row —
// generation then falls back to the source's default split (the pre-backfill
// behavior).
exports.down = knex =>
  knex.raw(/*sql*/ `
    UPDATE subscriptions
      SET defaults = defaults - 'benefit'
      WHERE period_unit IS NOT NULL AND defaults IS NOT NULL;
  `);
