name: Test bookkeper

on: [workflow_dispatch, push]

jobs:
  build:
    name: Build and test bookkeeper
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:11.8
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 15488:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #- uses: actions/cache@v3
      #  id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      #  with:
      #    path: node_modules:./yarn/cache
      #    key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #    restore-keys: |
      #      ${{ runner.os }}-yarn-

      - name: Use Node.js 14.15.5
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.5

      - name: Build deps
        run: yarn

      - name: Setup CI env
        run: cp .env.ci .env

      - name: Setup database
        run: yarn migrate

      - name: Lint
        run: yarn lint

      - name: Build server
        run: yarn build-server
      
      - name: Build client
        run: yarn build-client

      - name: Start server
        run: ./script/start-server.sh

      - name: Run tests
        run: yarn test

      - name: Stop server
        run: ./script/stop-server.sh
    