name: Test bookkeper

on: [workflow_dispatch, push]

jobs:
  Build-Bookkeeper:
    name: Build and test bookkeeper
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

        - name: Use Node.js 14.15.5
          uses: actions/setup-node@v1
          with:
            node-version: 14.15.5

        - name: Build deps
          run: yarn

        - name: Build
          run: yarn build
