name: Test bookkeper

on: [workflow_dispatch, push]

jobs:
  build:
    name: Build and test bookkeeper
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres:14.3
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 15488:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        id: bun-cache # use this to check for `cache-hit` (`steps.bun-cache.outputs.cache-hit != 'true'`)
        with:
          path: node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      
      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install deps
        run: bun install

      - name: Setup CI env
        run: cp .env.ci .env

      - name: Setup database
        run: |
          bun migrate
          bun seed

      - name: Lint
        run: bun lint-all

      - name: Build client
        run: bun build-client

      - name: Start server
        run: ./script/start-server.sh

      - name: Run tests
        id: run-tests
        continue-on-error: true
        run: bun test

      - name: Tests failed, dump server logs (See previous step for test logs)
        if: steps.run-tests.outcome != 'success'
        run: |
          echo "Tests failed, dumping server logs"
          cat log/server.log

      - name: Re-run tests in verbose mode
        if: steps.run-tests.outcome != 'success'
        run: |
          DEBUG=* bun test --silent=false
          exit 1

      - name: Stop server
        run: ./script/stop-server.sh
    