name: "Report build status to Slack"

on:
  workflow_run:
    workflows:
      [
        "Test Bookkeper",
      ]
    types:
      - completed

jobs:
  report:
    name: "Report build status to Slack"
    runs-on: ubuntu-22.04
    if: |
      github.event.workflow_run.conclusion != 'success' &&
      github.event.workflow_run.conclusion != 'cancelled' &&
      github.event.workflow_run.conclusion != 'skipped'

    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ${{ github.event.workflow_run.head_commit.message }}
          SLACK_TITLE: Build failed
